workerBench/workerBenchProject

public/mypage/css/style.css
views/mypage/header.ejs
views/mypage/myPage.html
views/mypage/myWishList.html
views/mypage/review.html

- Issue 번호를 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

mypage > dev

---

public/teacher/js/teacher-manage-complete.js
public/teacher/js/teacher-manage-incomplete.js
public/teacher/js/teacher-register.js
public/teacher/js/teacher-workshop-information.js
public/teacher/js/teacher-workshop.js
src/admin/admin.service.ts
src/auth/auth.service.ts
src/teacher/dto/createWorkshopsDto.ts
src/teacher/teacher.controller.ts
src/teacher/teacher.module.ts
src/teacher/teacher.repository.ts
src/teacher/teacher.service.ts

Fix :  merge 버그 수정
Fix :  merge 버그 수정

Fix :  merge 버그 수정

---

package-lock.json
public/admin/js/admin-manage.js
public/admin/js/header.js
src/admin/admin-render.controller.ts
src/auth/auth.controller.ts
src/auth/auth.service.ts
views/admin/admin-manage.ejs
views/admin/header.ejs
views/auth/non-auth-or-login-admin.ejs
views/workshops/workshop-detail.ejs

관리자 계정 삭졔 api 를 프론트와 연결해 두었습니다.  public/admin/js/admin-manage.js 입니다.
동적 랜더링의 경우 mypage 모듈 쪽을 제외하면 1차적으로 완성하였습니다.
관리자 계정 삭제 api 추가.
동적 랜더링 추가.
- 내용을 적어주세요.
- 내용을 적어주세요.

Auth 관리자 계정 삭제 api 프론트 연결. "마이페이지" 관련 페이지 제외한 동적 랜더링 1차 완료

---

public/teacher/css/workshop-register.css
public/teacher/js/workshop-register.js
src/teacher/teacher.service.ts

워크샵 등록 api 버그 수정 및 css 수정
워크샵 등록 api 버그 수정 및 css 수정
- 내용을 적어주세요.
- 내용을 적어주세요.

teacher -> dev 워크샵 등록 api 버그 수정 및 css 수정

---

dataSource.ts
src/config/typeorm.config.service.ts
src/mypage/mypage.service.ts
src/teacher/teacher.controller.ts
src/teacher/teacher.service.ts
views/mypage/wish-list.ejs
views/mypage/workshops.ejs
views/teacher/workshop-register.ejs

마이 페이지에 접속했을 시, 로그인한 유저가 일반 유저라면 "강사 등록하기" 버튼을 보여주고, 로그인 유저가 강사로 등록된 계정이라면 "강사 관리 페이지" 버튼을 보여 줍니다.
추가로, teacher 모듈에서 UseGurads 를 사용하여 기존에 user_id 를 하드코딩으로 입력하던 것을 쿠키의 payload 에서 id 값을 꺼내서 사용하도록 변경하였습니다.
-유저의 타입 (user_type) 이 0이라면 "강사 등록하기", 유저의 타입이 1이라면 "강사 관리 페이지"
- teahcer 모듈에서 @UseGuards(JwtTeacherAuthGuard) 사용.
- 내용을 적어주세요.
- 내용을 적어주세요.

Auth 마이페이지 동적 랜더링 추가 및 teacher 모듈 UseGuards 채택

---

src/admin/admin.controller.ts
src/auth/auth.controller.ts
src/mypage/mypage.controller.ts
src/mypage/mypage.module.ts
src/mypage/mypage.service.ts
src/workshops/workshops.controller.ts

각 모듈별로 권한이 필요한 경우 UseGuard 적용.
mypage 모듈 '유저 찜목록 불러오기' SQL 작성
api 에 따라서 권한이 필요하지 않은 경우(메인 페이지 등), 유저 권한이 필요한 경우(마이 페이지), 강사 권한이 필요한 경우(강사 페이지),
등 영역에 따라 필요한 권한이 다름. 이에 따라 Guard 를 api 의 속성에 맞게 배치.
- 내용을 적어주세요.
- 내용을 적어주세요.

Auth 각 모듈 controller 별로 UseGuard 가 필요한 곳에 가드 부착.

---

public/teacher/css/workshop-register.css
public/teacher/js/workshop-register.js
src/teacher/teacher.controller.ts
src/teacher/teacher.service.ts
views/teacher/workshop-register.ejs

업체등록 api에서 업체 등록시 테이블에 저장되면서 id를 찾아서 application 에 업체id와 teacherId가 저장되면 teacher쪽의 application_company_id가 추가된다.  
그리고 워크샵 등록 서브 이미지 넣는 페이지 추가 
업체등록 api 수정 및 워크샵 등록 서브 이미지 넣는 페이지 추가
teacher쪽의 application_company_id가 처음에 0이면 업체등록 버튼이 활성화되고 등록을하면 application_company_id가 company_Id로 변경된다.

teacher -> dev 업체등록 api 수정 및 워크샵 등록 서브 이미지 넣는 페이지 추가

---

public/admin/css/admin-login.css
public/auth/css/login.css
public/auth/css/password-change.css
public/auth/css/password-reset.css
public/auth/css/signup.css
public/teacher/css/teacher-register.css
views/admin/header.ejs
views/auth/header.ejs
views/mypage/workshops.ejs
views/teacher/header.ejs

header 색상 및 로고 통일
- header 색상 및 로고 통일 (로그인 등 버튼 포함)
- 내용을 적어주세요.
- 추후 페이지에 따라 색상 코드가 정확히 일치하지 않는 부분과 footer 추가 예정
(현재 footer는 마이페이지에만 있음)

Design: header 색상 및 로고 통일

---

public/teacher/css/company-register.css
public/teacher/css/header.css
public/teacher/css/teacher-manage-complete.css
public/teacher/css/teacher-manage-incomplete.css
public/teacher/css/teacher-workshop-information.css
public/teacher/css/teacher-workshop.css
public/teacher/css/workshop-register.css
public/teacher/js/company-register.js
public/teacher/js/teacher-manage-complete.js
public/teacher/js/teacher-manage-incomplete.js
public/teacher/js/teacher-register.js
public/teacher/js/teacher-workshop-information.js
public/teacher/js/teacher-workshop.js
public/teacher/js/workshop-register.js
src/teacher/teacher.controller.ts
src/teacher/teacher.service.ts
views/teacher/teacher-manage-complete.ejs
views/teacher/teacher-manage-incomplete.ejs
views/teacher/teacher-workshop-information.ejs
views/teacher/teacher-workshop.ejs
views/teacher/workshop-register.ejs

Design : 페이지 css 수정
Design : 페이지 css 수정

teacher -> dev Design : 페이지 css 수정

---

public/mypage/css/style.css
public/mypage/css/workshop-list.css
public/mypage/js/workshops.js
src/mypage/dtos/payment.dto.ts
src/mypage/mypage.controller.ts
src/mypage/mypage.module.ts
src/mypage/mypage.service.ts
views/mypage/header.ejs
views/mypage/workshops.ejs

마이페이지 결제 기능 구현(1차) + 수강 예정 / 완료 워크샵 API 및 프론트 통신
- 마이페이지 결제 기능 구현(1차): merchant_uid가 현재는 workshopDetail_id과 동일, db에 저장하지 않음 (변경 예정)
- 수강 예정 / 완료 워크샵 API 수정 & 프론트 통신 연결: 상세 내역 조회 시 모달 창 구현
- 마이 페이지 워크샵 목록 css 수정: 수강 예정 / 완료 탭 분리, 기타 디자인 수정
- 내용을 적어주세요.
- 마이페이지 결제 기능 구현(1차): merchant_uid가 현재는 workshopDetail_id과 동일, db에 저장하지 않음 (변경 예정)
=> order entity column에 merchant_uid가 추가됨에 따라 난수로 저장할 예정

마이페이지 결제 기능 구현(1차) + 수강 예정 / 완료 워크샵 API 및 프론트 통신

---

public/teacher/css/workshop-register.css
public/teacher/js/workshop-register.js
public/workshops/js/workshop-detail.js
src/auth/auth.service.ts
src/entities/order.ts
src/entities/user.ts
src/entities/workshop-instance.detail.ts
src/teacher/teacher.controller.ts
src/teacher/teacher.service.ts
src/workshops/workshops.controller.ts
src/workshops/workshops.service.ts
views/teacher/workshop-register.ejs
views/workshops/workshop-detail.ejs

workshop_instance_detail 과 order 테이블의 관계 mapping 추가, Feat: 워크샵 등록 시 
s3 에 동영상 추가 완료. 현재 동영상 링크를 가져와 html 에 보여주는 작업 진행 중
workshop_instance_detail 과 order 테이블에 서로의 관계를 mapping 해줬음.
joinColumn 은 order 테이블에 추가됨.
- 내용을 적어주세요.
- 내용을 적어주세요.

Auth workshop_instance_detail / order 관계 매핑 추가 및 동영상 등록 작업 중

---

dataSource.ts
public/teacher/css/teacher-manage-complete.css
public/teacher/css/teacher-manage-incomplete.css
public/teacher/css/teacher-workshop-information.css
public/teacher/js/teacher-manage-complete.js
public/teacher/js/teacher-manage-incomplete.js
public/teacher/js/teacher-workshop-information.js
public/teacher/js/teacher-workshop.js
src/config/typeorm.config.service.ts
src/teacher/teacher.controller.ts
src/teacher/teacher.service.ts
views/teacher/teacher-workshop-information.ejs

업체 검색하기 및 등록된 업체에 신청하기,신청한 업체목록 보기, 신청한 업체 수락하기, 워크샵 신청 취소하기 api 추가
1. 업체 검색할때 예를들어 라마바 회사와 라비안 회사가 있을경우 라만 검색했을때 둘다 검색되도록 했습니다.
2. 등록된 업체에 신청하기를 누르면 해당 company테이블의 id가 company_application의 company_id에 저장됩니다.
(업체가 있는경우)
3. 신청한 업체목록 보기를 누르면 company_application에 자신의 company_id를 다 볼수있습니다.
4. 신청한 업체 수락하기 버튼을 누르면 해당 강사는 company_application에 저장된 값이 완전히 사라지고 teacher테이블에 affiliation_company_id값이 자신의 company_id 값으로 업데이트 됩니다. 그러면 해당 강사는 자신의 업체에 소속이 되고
자신의 회사명과 예금주명에 썻던 이름이 보여지게 됩니다.(회사가 비슷한 이름일경우 더 자세히 찾기 위해)
5. 워크샵 신청 취소하기를 누르면 해당강사의 company_application의 id값이 완전히 사라지게 됩니다.
자신의 업체 목록을 볼때 원래라면 company테이블에 값이 Mycompany에 저장되어서 보여졌었는데 소속업체일 경우 company테이블에 값이 들어있지 않아서 Mycompany가 null값이 되므로 소속된 company의 id를 가져와 company라는 변수에 저장되기 때문에 Mycompany와 company 두개가 있습니다.
css 부족합니다.

Teacher -> dev 업체 검색하기 및 등록된 업체에 신청하기,신청한 업체목록 보기, 신청한 업체 수락하기, 워크샵 신청 취소하기 api 추가

---

public/workshops/css/workshop-detail.css
public/workshops/js/workshop-detail.js
views/workshops/workshop-detail.ejs

워크샵 등록 시 동영상 첨부 기능 추가 및 워크샵 상세 페이지에서 동영상 보여주기 화면 추가.
워크샵 등록 시 동영상을 input 용 버킷으로 업로드 하면, 람다 함수와 mediaConvert 를 사용하여 hls, m3u8 파일로 전환하여
output 용 버킷에 저장.
- 내용을 적어주세요.
- 내용을 적어주세요.

Auth 워크샵 등록 시 동영상 첨부 기능 추가 및 워크샵 상세 페이지에서 동영상 보여주기 화면 추가

---

public/mypage/js/workshops.js
public/workshops/js/workshop-detail.js
src/database/seeds/main-dummy.data.seeder.ts
src/entities/review.ts
src/mypage/dtos/review.dto.ts
src/mypage/mypage.controller.ts
src/mypage/mypage.service.ts
src/workshops/workshops.service.ts
views/mypage/workshops.ejs

Auth 마이페이지 리뷰 작성 기능 추가 및 review 엔티티 칼럼 수정
리뷰 작성 기능 추가. 썸네일 유무는 작성자의 임의로 선택 가능.
review 엔티티에 "workshop_instance_detail_id" 칼럼(필드)을 추가하였음.
동일한 유저가 동일한 워크샵을 여러 번 수강할 수도 있기에, 어떤 instance_detail 에 대한 리뷰인지도 명시를 해야 함.
review 엔티티에 "workshop_instance_detail_id" 칼럼(필드)을 추가
추가로, 워크샵 상세 페이지에서 후기를 불러오는 함수 (workshops.service.ts / getWorkshopReviews()) 의 경우, 리뷰에 썸네일 이미지가 
존재하는가 그렇지 않은가에 대한 예외 처리를 추가함
- 내용을 적어주세요.

Auth 마이페이지 리뷰 작성 기능 추가 및 review 엔티티 칼럼 수정

---

public/teacher/css/teacher-manage-complete.css
public/teacher/css/teacher-manage-incomplete.css
public/teacher/css/teacher-workshop-information.css
public/teacher/css/teacher-workshop.css
public/teacher/css/workshop-register.css
public/teacher/js/teacher-workshop-information.js
public/teacher/js/teacher-workshop.js
src/teacher/teacher.controller.ts
src/teacher/teacher.service.ts
views/teacher/teacher-manage-complete.ejs
views/teacher/teacher-manage-incomplete.ejs
views/teacher/teacher-workshop-information.ejs
views/teacher/teacher-workshop.ejs
views/teacher/workshop-register.ejs

- Teacher 모듈에서 모든 업체 조회 API 생성
- 강사페이지 CSS 개선 (나의 워크샵 목록, 강사 및 업체 정보)

Admin > Dev // Teacher 모듈에서 모든 업체 조회 API 생성 // 강사페이지 CSS 개선

---

public/admin/js/workshops-approval.js
public/teacher/css/teacher-workshop.css
public/teacher/js/teacher-workshop-information.js
public/teacher/js/teacher-workshop.js
src/admin/admin.controller.ts
src/admin/admin.service.ts
src/teacher/teacher.controller.ts
src/teacher/teacher.service.ts
views/teacher/teacher-workshop-information.ejs

- 강사 페이지 일부 오류 수정 
- 업체 검색 시 company_type : 0 인 것만 가져오기,
- 워크숍 삭제 시 delete 메소드 아닌 patch 메소드 사용 (status 만 변경)

Admin > Dev //Design: 강사 페이지 일부 오류 수정 // 업체 검색 시 company_type : 0 인 것만 가져오기, 워크숍 삭제 시 delete 메소드 아닌 patch 메소드 사용 (status 만 변경)

---

public/teacher/css/teacher-workshop.css
public/teacher/js/teacher-workshop.js
src/teacher/teacher.service.ts

강사 전용 페이지 워크샵 상세 보기 CSS 수정
- 내용을 적어주세요.
- 내용을 적어주세요.

Fix: 강사 전용 페이지 워크샵 상세 보기 CSS 수정

---

public/teacher/css/teacher-manage-complete.css

Fix: 강사 - 수강문의 관리 완료 페이지에서 css 수정
수강 문의 기록의 css 를 수정
- 내용을 적어주세요.
- 내용을 적어주세요.

강사 - 수강문의 관리 완료 페이지에서 css 수정

---

dataSource.ts
public/main/css/main.css
public/main/js/main.js
public/mypage/css/wish-list.css
public/mypage/css/workshop-list.css
public/mypage/js/workshops.js
public/workshops/css/workshop-detail.css
public/workshops/css/workshop-search.css
public/workshops/js/workshop-detail.js
src/config/typeorm.config.service.ts
src/mypage/mypage.service.ts
src/workshops/workshops.render.controller.ts
views/mypage/workshops.ejs
views/workshops/workshop-detail.ejs

- 워크샵 신청 시 주소 입력창 노출 여부 수정 / 유효성 검사 보완 등
- 워크샵 신청 시 주소 입력창 노출 여부 수정: 온라인 워크샵일 때는 주소창을 숨김
- 프론트 통신 시 유효성 검사 보완 (워크샵 신청 & 결제 시)
- 워크샵 썸네일 카드 이미지 높이 고정
- 마이페이지 워크샵 목록 조회 시 최신순으로 정렬
- 내용을 적어주세요.
- 내용을 적어주세요.

워크샵 신청 시 주소 입력창 노출 여부 수정 / 유효성 검사 보완

---

dataSource.ts
public/teacher/css/company-register.css
public/teacher/js/company-register.js
public/teacher/js/teacher-register.js
public/teacher/js/workshop-register.js
public/workshops/css/workshop-detail.css
public/workshops/js/workshop-detail.js
src/config/typeorm.config.service.ts
src/teacher/teacher.controller.ts
src/teacher/teacher.service.ts
views/teacher/company-register.ejs
views/teacher/teacher-register.ejs
views/teacher/workshop-register.ejs
views/workshops/workshop-detail.ejs
views/workshops/workshop-search.ejs

1차 유저 테스트 이후 버그 fix. 주로 프론트 단 입력값 유효성 검사에 대한 피드백 반영
워크샵 등록 신청 시 최소, 최대 인원, 소요 시간, 가격 등 숫자 타입의 입력값이 필요한 input 에서
해당 숫자가 정수인지, 최대 값이 최소 값보다 많은 지 등 유효성 검사를 하는 로직을 프론트에 추가.
일반 유저가 워크샵 수강 문의 신청 작성 시, 희망 수강 인원이 워크샵의 정해진 최소, 최대 인원에 포함되지 않아도 등록이 되었던 버그를 수정.
워크샵 검색 시, 각 태그에 '-- 전체 --' 옵션 추가
- 내용을 적어주세요.
- 내용을 적어주세요.

Auth 1차 유저 테스트 이후 버그 fix. 주로 프 론트 단 입력값 유효성 검사에 대한 피드백 반영

---

public/teacher/js/workshop-register.js
public/workshops/js/workshop-detail.js
src/auth/auth.service.ts
src/config/typeorm.config.service.ts
src/entities/workshop-instance.detail.ts
src/entities/workshop.ts
src/teacher/dto/teacher-workshops-video.dto.ts
src/teacher/dto/teacher-workshops.dto.ts
src/teacher/teacher.controller.ts
src/teacher/teacher.render.controller.ts
src/teacher/teacher.service.ts
src/workshops/workshops.controller.ts
src/workshops/workshops.service.ts
views/auth/go-to-register-company.ejs

Auth 워크샵 등록 / 워크샵 수강 신청 등록 시 프론트, 백엔드에서 유효성 검사 강화
워크샵 등록 시 최소 인원이 최대 인원을 넘지 않도록, 그 외에도 숫자를 입력하는 경우 양의 정수만 입력할 수 있도록 변경.
워크샵 수강 신청 작성 시 희망 인원이 워크샵의 제한 최소/최대 인원을 위배할 경우 이를 경고해 주는 유효성 검사 로직 추가.
- 내용을 적어주세요.
- 내용을 적어주세요.

Auth 워크샵 등록 / 워크샵 수강 신청 등록 시 프론트, 백엔드에서 유효성 검사 강화

---

.gitignore
docker-compose.yml
public/admin/js/header.js
public/teacher/css/workshop-register.css
public/teacher/js/teacher-workshop.js
public/teacher/js/workshop-register.js
views/teacher/workshop-register.ejs

워크샵 등록 페이지 css 수정
- 내용을 적어주세요.
- 내용을 적어주세요.

Fix: 워크샵 등록 페이지 css 수정

---

public/mypage/js/wish-list.js

마이페이지 접속 시 찜 목록이 없다면 나오는 알림창 수정
기존에는 " 에러 코드 404, message: 현재 찜 목록이 없습니다 " 라고 출력.
이를 "현재 찜 목록이 없습니다" 라고 만 출력되도록 변경
- 내용을 적어주세요.
- 내용을 적어주세요.

Fix 마이페이지 접속 시 찜 목록이 없다면 나오는 알림창 수정

---

.github/workflows/main.yml

workflows main.yml actions/checkout@v2 버전 3->2 로 변경
// workflows > main.yml
---
uses: actions/checkout@v2
---
- 내용을 적어주세요.

Fix: workflows main.yml actions/checkout@v2 버전 3->2 로 변경

---

public/mypage/js/wish-list.js

유저 찜 목록 페이지 접속 시 찜 목록이 없다면 출력되는 알림창 문구 변경

Fix: 유저 찜 목록 페이지 접속 시 찜 목록이 없다면 출력되는 알림창 문구 변경

---

public/mypage/js/wish-list.js

Fix: 마이페이지 찜목록 알림창 문구 수정

---

public/mypage/js/wish-list.js

Fix: 마이 페이지 찜 목록 알림창 문구 수정

---

public/mypage/js/wish-list.js

- Issue 번호를 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

Fix: git action 시험용 커밋

---

public/mypage/js/wish-list.js

- Issue 번호를 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

Action: 깃 액션용 커밋

---

public/mypage/js/wish-list.js

Fix: main merge github actions 테스트용 수정
- public > js > wishlist:  error message alert 내용 수정
- 내용을 적어주세요.
- 내용을 적어주세요.

Fix: main merge github actions 테스트용 수정

---

public/mypage/js/wish-list.js

GitActionTest: 깃 액션 작동 테스트용 커밋
Ec2 우분투 서버의 docker image 최신화 실험용

GitActionTest: 깃 액션 작동 테스트용 커밋

---

README.md

README 사용한 아키텍처 이미지 링크 수정
사용한 아키텍처 수정으로 인한 이미지 수정.
https, docker, CI/CD 추가

Fix: README 사용한 아키텍처 이미지 링크 수정

---

README.md
lambda_image_resize/index.js
lambda_image_resize/package-lock.json
lambda_image_resize/package.json
lambda_video_hls/index.js
lambda_video_hls/package-lock.json
lambda_video_hls/package.json
src/config/typeorm.config.service.ts

AWS Lambda 함수에서 사용된 이미지 리사이징, 영상 컨버팅 코드를 프로젝트의 루트 위치에 추가.
해당 코드는 프로젝트 내부에서는 작동하지 않음.
README 프로젝트 일정 이미지 삽입을 위해서 수정. 람다 함수 코드 추가로 인한 프로젝트 폴더 구조 변경

Hotfix 람다 함수 코드 추가, README 수정
